/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Product;

import Dao.ProductDAO;
import Model.Product;
import java.io.File;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author kumar
 */
public class ProductFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public ProductFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        lblPName = new javax.swing.JLabel();
        ComboCategary = new javax.swing.JComboBox<>();
        lblPCategary = new javax.swing.JLabel();
        ComobMeatal = new javax.swing.JComboBox<>();
        lbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPWeight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPPrice = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        btnAddProduct1 = new javax.swing.JButton();
        ComboSize = new javax.swing.JComboBox<>();
        ComoDesign = new javax.swing.JComboBox<>();
        ComboCarat = new javax.swing.JComboBox<>();
        txtTodyPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Product ");

        lblPName.setText("Product name");

        ComboCategary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rings", "Bracelets", "Bangles", "Earrings", "Anklets (Payal)", "Nose Rings (Nath)", "Maang Tikka & Head Jewelry", "Bridal Sets", "Men’s Jewelry" }));
        ComboCategary.addActionListener(this::ComboCategaryActionPerformed);

        lblPCategary.setText("Categary");

        ComobMeatal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold", "Silver", "Platinum" }));
        ComobMeatal.addActionListener(this::ComobMeatalActionPerformed);

        lbl.setText("Metal");

        lbl1.setText("Size");

        lbl2.setText("Design");

        lbl3.setText("Carrete");

        lbl4.setText("Today Price");

        jLabel6.setText("Weight");

        txtPWeight.addActionListener(this::txtPWeightActionPerformed);

        jLabel7.setText("Price");

        txtPPrice.addActionListener(this::txtPPriceActionPerformed);

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(this::btnAddProductActionPerformed);

        btnAddProduct1.setText("Update Product");
        btnAddProduct1.addActionListener(this::btnAddProduct1ActionPerformed);

        ComboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        ComoDesign.addActionListener(this::ComoDesignActionPerformed);

        ComboCarat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        txtTodyPrice.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPCategary, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPPrice)
                    .addComponent(txtPWeight)
                    .addComponent(ComobMeatal, 0, 175, Short.MAX_VALUE)
                    .addComponent(ComboCategary, 0, 1, Short.MAX_VALUE)
                    .addComponent(txtPName)
                    .addComponent(ComboSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComoDesign, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboCarat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTodyPrice))
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnAddProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComobMeatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPCategary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCategary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComoDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCarat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTodyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPWeightActionPerformed

    private void ComobMeatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComobMeatalActionPerformed
        // TODO add your handling code here:
        String metal = ComobMeatal.getSelectedItem().toString();
        ComboCarat.removeAllItems();

        if (metal.equals("Gold")) {
            ComboCarat.addItem("24K");
            ComboCarat.addItem("22K");
            ComboCarat.addItem("18K");
            ComboCarat.addItem("14K");
        } else if (metal.equals("Silver")) {
            ComboCarat.addItem("999");
            ComboCarat.addItem("925");
        } else if (metal.equals("Platinum")) {
            ComboCarat.addItem("950");
            ComboCarat.addItem("900");
        }
    }//GEN-LAST:event_ComobMeatalActionPerformed

    private void txtPPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPPriceActionPerformed

    private void ComboCategaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCategaryActionPerformed
        // TODO add your handling code here:
        String category = ComboCategary.getSelectedItem().toString();
        ComboSize.removeAllItems();

// Rings
        if (category.equals("Rings")) {
            ComboSize.addItem("6");
            ComboSize.addItem("7");
            ComboSize.addItem("8");
            ComboSize.addItem("9");
            ComboSize.addItem("10");
        } // Bracelets
        else if (category.equals("Bracelets")) {
            ComboSize.addItem("6.5 inch");
            ComboSize.addItem("7 inch");
            ComboSize.addItem("7.5 inch");
            ComboSize.addItem("8 inch");
        } // Bangles
        else if (category.equals("Bangels")) {
            ComboSize.addItem("2.2");
            ComboSize.addItem("2.4");
            ComboSize.addItem("2.6");
            ComboSize.addItem("2.8");
            ComboSize.addItem("2.10");
        } // Earrings (no size needed)
        else if (category.equals("Earrings")) {
            ComboSize.addItem("Small");
            ComboSize.addItem("Medium");
            ComboSize.addItem("Large");
        } // Anklets
        else if (category.equals("Anklets (Payal)")) {
            ComboSize.addItem("9 inch");
            ComboSize.addItem("10 inch");
            ComboSize.addItem("11 inch");
        } // Nose Rings
        else if (category.equals("Nose Rings (Nath)")) {
            ComboSize.addItem("Small");
            ComboSize.addItem("Medium");
            ComboSize.addItem("Large");
        } // Maang Tikka
        else if (category.equals("Maang Tikka & Head Jewelry")) {
            ComboSize.addItem("Standard Size");
        } // Bridal Sets
        else if (category.equals("Bridal Sets")) {
            ComboSize.addItem("Free Size");
        } // Men's Jewelry
        else if (category.equals("Men’s Jewelry")) {
            ComboSize.addItem("18 inch");
            ComboSize.addItem("20 inch");
            ComboSize.addItem("22 inch");
        }
        ComoDesign.removeAllItems();

// Rings
        if (category.equals("Rings")) {
            ComoDesign.addItem("Solitaire Ring");
            ComoDesign.addItem("Engagement Ring");
            ComoDesign.addItem("Band Ring");
            ComoDesign.addItem("Cocktail Ring");
        } // Bracelets
        else if (category.equals("Bracelets")) {
            ComoDesign.addItem("Chain Bracelet");
            ComoDesign.addItem("Cuff Bracelet");
            ComoDesign.addItem("Charm Bracelet");
            ComoDesign.addItem("Tennis Bracelet");
        } // Bangles
        else if (category.equals("Bangels")) {
            ComoDesign.addItem("Traditional Bangle");
            ComoDesign.addItem("Kada");
            ComoDesign.addItem("Stone Studded Bangle");
            ComoDesign.addItem("Gold Plain Bangle");
        } // Earrings
        else if (category.equals("Earrings")) {
            ComoDesign.addItem("Stud Earrings");
            ComoDesign.addItem("Hoop Earrings");
            ComoDesign.addItem("Drop Earrings");
            ComoDesign.addItem("Jhumka");
        } // Anklets
        else if (category.equals("Anklets (Payal)")) {
            ComoDesign.addItem("Chain Anklet");
            ComoDesign.addItem("Beaded Anklet");
            ComoDesign.addItem("Charm Anklet");
            ComoDesign.addItem("Traditional Payal");
        } // Nose Rings
        else if (category.equals("Nose Rings (Nath)")) {
            ComoDesign.addItem("Stud Nose Pin");
            ComoDesign.addItem("Hoop Nath");
            ComoDesign.addItem("Bridal Nath");
            ComoDesign.addItem("Diamond Nose Ring");
        } // Maang Tikka
        else if (category.equals("Maang Tikka & Head Jewelry")) {
            ComoDesign.addItem("Single Chain Maang Tikka");
            ComoDesign.addItem("Matha Patti");
            ComoDesign.addItem("Borla");
            ComoDesign.addItem("Passa");
        } // Bridal Sets
        else if (category.equals("Bridal Sets")) {
            ComoDesign.addItem("Gold Bridal Set");
            ComoDesign.addItem("Kundan Bridal Set");
            ComoDesign.addItem("Polki Bridal Set");
            ComoDesign.addItem("Diamond Bridal Set");
        } // Men's Jewelry
        else if (category.equals("Men’s Jewelry")) {
            ComoDesign.addItem("Men's Ring");
            ComoDesign.addItem("Men's Chain");
            ComoDesign.addItem("Men's Bracelet");
            ComoDesign.addItem("Men's Kada");
        }

    }//GEN-LAST:event_ComboCategaryActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        String name = txtPName.getText();
        String categary = ComboCategary.getSelectedItem().toString();
        String metal = ComobMeatal.getSelectedItem().toString();
        String weight = txtPWeight.getText();
        String price = txtPPrice.getText().trim();
        String size = ComboSize.getSelectedItem().toString();
        String design = ComoDesign.getSelectedItem().toString();
        String carat = ComboCarat.getSelectedItem().toString();
        String todayprice = txtTodyPrice.getText();
//        String quntity = txtPQuntity.getText().trim();
//       String ImagePath = ImageChooser.getText();

        if (name.isEmpty() || categary.isEmpty() || metal.isEmpty() || weight.isEmpty()|| todayprice.isEmpty() ||size.isEmpty() || design.isEmpty()|| carat.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Please fill all fields");
            return;
        }

        double Price;
        try {
            Price = Double.parseDouble(price);
            if (Price <= 0) {
                JOptionPane.showMessageDialog(this, "Price must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be contain valid digits");
            return;
        }

        double TodayPrice;
        try {
            TodayPrice = Double.parseDouble(todayprice);
            if (TodayPrice <= 0) {
                JOptionPane.showMessageDialog(this, "Toady Price must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Toady Price must be contain valid digits");
            return;
        }
        Double Weight;
        try {
            Weight = Double.parseDouble(weight);
            if (Weight <= 0) {
                JOptionPane.showMessageDialog(this, "Weight must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Weight  must be contain valid digits");
            return;
        }

        Product pro = new Product();
        pro.setName(name);
        pro.setCategary(categary);
        pro.setMetal(metal);
        pro.setWeight(Weight);
        pro.setPrice(Price);
        pro.setCarat(carat);
        pro.setDesign(design);
        pro.setSize(size);
        pro.setTodayPrice(TodayPrice);

        ProductDAO dao = new ProductDAO();
        String res = null;
        try {
            res = dao.addProduct(pro);
            if(res != null){
                JOptionPane.showMessageDialog(this,"New Product added with Product id"+res);
            }else{
                            JOptionPane.showMessageDialog(this, "Product not added please try agian");
            }
        } catch (SQLException ex) {
            System.getLogger(ProductFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnAddProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProduct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct1ActionPerformed

    private void ComoDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComoDesignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComoDesignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCarat;
    private javax.swing.JComboBox<String> ComboCategary;
    private javax.swing.JComboBox<String> ComboSize;
    private javax.swing.JComboBox<String> ComoDesign;
    private javax.swing.JComboBox<String> ComobMeatal;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddProduct1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblPCategary;
    private javax.swing.JLabel lblPName;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPPrice;
    private javax.swing.JTextField txtPWeight;
    private javax.swing.JTextField txtTodyPrice;
    // End of variables declaration//GEN-END:variables
}
