/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Employee;

import Dao.EmployeeDAO;
import Model.Employee;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kumar
 */
public class EmployeeDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeDetails.class.getName());

    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEmName = new javax.swing.JTextField();
        txtEmPhone = new javax.swing.JTextField();
        txtEmAddress = new javax.swing.JTextField();
        txtErSalary = new javax.swing.JTextField();
        txtEmpFather = new javax.swing.JTextField();
        txtEmpIdNo = new javax.swing.JTextField();
        txtExperience = new javax.swing.JTextField();
        ComboEmpId = new javax.swing.JComboBox<>();
        comboEmpSex = new javax.swing.JComboBox<>();
        ComboEmpEduction = new javax.swing.JComboBox<>();
        jDateEmJoinDate = new com.toedter.calendar.JDateChooser();
        btnDeleteEmp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddEmp = new javax.swing.JButton();
        btnfind = new javax.swing.JButton();
        btnUpdateEmp = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        ComboEmpRole = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Empolyee");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Employee Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Contact");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Father's Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Role");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Id Type");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Salary");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Id No");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Education");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Date");

        txtEmName.addActionListener(this::txtEmNameActionPerformed);

        txtEmPhone.addActionListener(this::txtEmPhoneActionPerformed);

        txtEmAddress.addActionListener(this::txtEmAddressActionPerformed);

        txtErSalary.addActionListener(this::txtErSalaryActionPerformed);

        txtEmpFather.addActionListener(this::txtEmpFatherActionPerformed);

        txtEmpIdNo.addActionListener(this::txtEmpIdNoActionPerformed);

        txtExperience.addActionListener(this::txtExperienceActionPerformed);

        ComboEmpId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ID Type", "Aadhaar Card", "PAN Card", "Voter ID Card", "Driving License", "Passport" }));
        ComboEmpId.addActionListener(this::ComboEmpIdActionPerformed);

        comboEmpSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        comboEmpSex.addActionListener(this::comboEmpSexActionPerformed);

        ComboEmpEduction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10th Pass", "12th Pass", "Diploma", "ITI", "Graduate (BA / BSc / BCom)", "BCA", "BBA", "B.Tech / BE", "Post Graduate (MA / MSc / MCom)", "MCA", "MBA", "Professional (CA / CS)", "Other" }));

        btnDeleteEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteEmp.setText("Delete");
        btnDeleteEmp.addActionListener(this::btnDeleteEmpActionPerformed);

        btnAddEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddEmp.setText("Save");
        btnAddEmp.addActionListener(this::btnAddEmpActionPerformed);

        btnfind.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnfind.setText("Search Emp");
        btnfind.addActionListener(this::btnfindActionPerformed);

        btnUpdateEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateEmp.setText("Update");
        btnUpdateEmp.addActionListener(this::btnUpdateEmpActionPerformed);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel49.setText("Experiance");

        ComboEmpRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Salesman", "Cashier", "Store Keeper", "Accountant", "Karigar", "Supplier Manager", "Guard", "Customer Support" }));
        ComboEmpRole.addActionListener(this::ComboEmpRoleActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeleteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboEmpRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtErSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboEmpId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmpIdNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboEmpEduction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExperience, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateEmJoinDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboEmpSex, 0, 262, Short.MAX_VALUE)
                                    .addComponent(txtEmName)
                                    .addComponent(txtEmpFather))))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEmpSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboEmpRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtErSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboEmpEduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateEmJoinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmNameActionPerformed

    private void txtEmPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmPhoneActionPerformed

    private void txtEmAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmAddressActionPerformed

    private void txtErSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtErSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtErSalaryActionPerformed

    private void txtEmpFatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpFatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpFatherActionPerformed

    private void txtEmpIdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpIdNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpIdNoActionPerformed

    private void txtExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceActionPerformed

    private void btnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpActionPerformed
        // TODO add your handling code here:
        EmployeeDelete empdel = new EmployeeDelete();
        empdel.setVisible(true);
        
    }//GEN-LAST:event_btnDeleteEmpActionPerformed

    private void btnUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmpActionPerformed
        // TODO add your handling code here:
        UpdateEmployeFram UEF = new UpdateEmployeFram();
        UEF.setVisible(true);
    }//GEN-LAST:event_btnUpdateEmpActionPerformed

    private void ComboEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEmpIdActionPerformed

    private void ComboEmpRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEmpRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEmpRoleActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
        String name = txtEmName.getText();
        String father = txtEmpFather.getText();
        String sex = comboEmpSex.getSelectedItem().toString();
        String contact = txtEmPhone.getText().trim();
        String role = ComboEmpRole.getSelectedItem().toString();
        String address = txtEmAddress.getText();
        String getsalary = txtErSalary.getText().trim();
        String IdName = ComboEmpId.getSelectedItem().toString();
        String idNo = txtEmpIdNo.getText();
        String education = ComboEmpEduction.getSelectedItem().toString();
        String Experiance = txtExperience.getText();
        Date date = jDateEmJoinDate.getDate();

        if (name.isEmpty() || role.isEmpty() || address.isEmpty() || father.isEmpty() || sex.isEmpty() || education.isEmpty() || Experiance.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields");
            return;
        }

//       Select ID Type
//Aadhaar Card
//PAN Card
// Voter ID Card
//Driving License
//Passport
        if (ComboEmpId.getSelectedIndex() == 0 || IdName.equals("Select ID Type")) {
            JOptionPane.showMessageDialog(this, "Please select ID type");
            return;
        }

        if(idNo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter ID no");
            return;
        }
        if (IdName.equals("Aadhaar Card")) {
            if (!idNo.matches("\\d{12}")) {
                JOptionPane.showMessageDialog(this, "Aadhaar must be 12 digits");
                return;
            }
        }

        if (IdName.equals("PAN Card")) {
            if (!idNo.matches("[A-Z]{5}[0-9]{4}[A-Z]{1}")) {
                JOptionPane.showMessageDialog(this, "Invalid PAN NO \n ( Correct formate is ABCDE1234F )");
                return;
            }
        }
        if (IdName.equals("Voter ID Card")) {
            if (!idNo.matches("[A-Z]{3}[0-9]{7}")) {
                JOptionPane.showMessageDialog(this, "Invalid Voter ID NO \n ( Correct formate is ABC1234567 )");
                return;
            }
        }
        if (IdName.equals("Driving License")) {
            if (!idNo.matches("[A-Z]{2}[0-9]{2}[0-9]{4}[0-9]{7}")) {
                JOptionPane.showMessageDialog(this, "Invalid Driving License \n correct formate is BR0120200001234");
                return;
            }
        }
        if (IdName.equals("Passport")) {
            if (!idNo.matches("[A-Z][0-9]{7}")) {
                JOptionPane.showMessageDialog(this, "Invalid Passport \n  correct format is A1234567");
                return;
            }
        }

        if (date == null) {
            JOptionPane.showMessageDialog(this, "Please Enter Joining date");
            return;
        }
        if (!contact.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Phone number must be 10 dgits");
            return;
        }

        double salary;
        try {
            salary = Double.parseDouble(getsalary);
            if (salary <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salary must be contain valid digits");
            return;
        }

        LocalDate localDate = date.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        Employee employee = new Employee();
        employee.setName(name);
        employee.setContact(contact);
        employee.setRole(role);
        employee.setAddress(address);
        employee.setSalary(salary);
        employee.setJoinDate(localDate);
        employee.setFatherName(father);
        employee.setSex(sex);
        employee.setEducation(education);
        employee.setExperience(Experiance);
        employee.setIdName(IdName);
        employee.setIdNo(idNo);

        EmployeeDAO dao = new EmployeeDAO();
        try {
            if (dao.chaekEmpExixstsDuringAdd(employee)) {
                JOptionPane.showMessageDialog(this, "Employee alreday exits");
            } else {
                String res = dao.insertEmployee(employee);
                if (res != null) {
                    JOptionPane.showMessageDialog(this, "Employee added successfully \n Employee id is " + res);
                } else {
                    JOptionPane.showMessageDialog(this, "Employee not added");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void comboEmpSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEmpSexActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
        FindEmployeeFram find = new FindEmployeeFram();
        find.setVisible(true);
    }//GEN-LAST:event_btnfindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEmpEduction;
    private javax.swing.JComboBox<String> ComboEmpId;
    private javax.swing.JComboBox<String> ComboEmpRole;
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnUpdateEmp;
    private javax.swing.JButton btnfind;
    private javax.swing.JComboBox<String> comboEmpSex;
    private com.toedter.calendar.JDateChooser jDateEmJoinDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtEmAddress;
    private javax.swing.JTextField txtEmName;
    private javax.swing.JTextField txtEmPhone;
    private javax.swing.JTextField txtEmpFather;
    private javax.swing.JTextField txtEmpIdNo;
    private javax.swing.JTextField txtErSalary;
    private javax.swing.JTextField txtExperience;
    // End of variables declaration//GEN-END:variables
}
