/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Employee.suppliers;

import Dao.ProductDAO;
import Dao.SupplierDAO;
import Model.Product;
import Model.purchase.SupplierQutation;
import Model.purchase.SupplieOrderItem;
import Model.purchase.Supplier;
import Model.purchase.SupplierOrder;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import ui.Product.ProductFind;
import ui.Product.ProductFrame;

/**
 *
 * @author kumar
 */
public class SupplierOrderfram extends javax.swing.JFrame {

    List<JTextField> productFields = new ArrayList<>();
    List<JTextField> quantityFields = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SupplierOrderfram.class.getName());

    /**
     * Creates new form SupplierOrder
     */
    public SupplierOrderfram() {
        initComponents();
        panelControl.setLayout(new BoxLayout(panelControl, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtproDesign = new javax.swing.JTextField();
        txtNewWeight = new javax.swing.JTextField();
        txtProMetal = new javax.swing.JTextField();
        txtprocarate = new javax.swing.JTextField();
        txtProCategary = new javax.swing.JTextField();
        txtPrName = new javax.swing.JTextField();
        txtProId = new javax.swing.JTextField();
        btnSeeproduct = new javax.swing.JButton();
        btnAddNewProduct = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        btnseeAllproduct = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtSupplierid = new javax.swing.JTextField();
        btnSeeproduct4 = new javax.swing.JButton();
        btnSeeproduct5 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        txtSupplierCompanyName = new javax.swing.JTextField();
        txtSupplierContact = new javax.swing.JTextField();
        txtSupplierGSTNo = new javax.swing.JTextField();
        txtSupplierAddress = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btnAddMore = new javax.swing.JButton();
        panelControl = new java.awt.Panel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        orderDate = new com.toedter.calendar.JDateChooser();
        delivertDate = new com.toedter.calendar.JDateChooser();
        paymentDate = new com.toedter.calendar.JDateChooser();
        comboPaymentMode = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        comboOrderStatus = new javax.swing.JComboBox<>();
        comboPerUnit = new javax.swing.JComboBox<>();
        txtTotalAMount = new javax.swing.JTextField();
        txtTotalPaid = new javax.swing.JTextField();
        txtAdvancePaymet = new javax.swing.JTextField();
        txtPaymetnId = new javax.swing.JTextField();
        txtDuePayment = new javax.swing.JTextField();
        txtRatePerUnit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        valitdDate = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Supplier Order");

        jLabel3.setText("Product Name");

        jLabel8.setText("Enter product id");

        jLabel9.setText("Product categary");

        jLabel10.setText("Weight");

        jLabel11.setText("Desgin");

        jLabel12.setText("Metal");

        jLabel13.setText("Carret");

        txtproDesign.addActionListener(this::txtproDesignActionPerformed);

        txtNewWeight.addActionListener(this::txtNewWeightActionPerformed);

        txtProMetal.addActionListener(this::txtProMetalActionPerformed);

        txtprocarate.addActionListener(this::txtprocarateActionPerformed);

        txtProCategary.addActionListener(this::txtProCategaryActionPerformed);

        txtPrName.addActionListener(this::txtPrNameActionPerformed);

        txtProId.addActionListener(this::txtProIdActionPerformed);

        btnSeeproduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeeproduct.setText("See product");
        btnSeeproduct.addActionListener(this::btnSeeproductActionPerformed);

        btnAddNewProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddNewProduct.setText("Add New Product");
        btnAddNewProduct.addActionListener(this::btnAddNewProductActionPerformed);

        jLabel15.setText("for New Weight");

        txtWeight.addActionListener(this::txtWeightActionPerformed);

        btnseeAllproduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnseeAllproduct.setText("See All Product");
        btnseeAllproduct.addActionListener(this::btnseeAllproductActionPerformed);

        jLabel16.setText("Enter Supplier id");

        txtSupplierid.addActionListener(this::txtSupplieridActionPerformed);

        btnSeeproduct4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeeproduct4.setText("supplier details");
        btnSeeproduct4.addActionListener(this::btnSeeproduct4ActionPerformed);

        btnSeeproduct5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeeproduct5.setText("Add New Supplier");
        btnSeeproduct5.addActionListener(this::btnSeeproduct5ActionPerformed);

        jLabel45.setText("Supplier Contact");

        jLabel46.setText("Supplier Name");

        jLabel47.setText("GST NO");

        jLabel48.setText("Address");

        jLabel49.setText("Company Name");

        txtSupplierName.addActionListener(this::txtSupplierNameActionPerformed);

        txtSupplierCompanyName.addActionListener(this::txtSupplierCompanyNameActionPerformed);

        txtSupplierContact.addActionListener(this::txtSupplierContactActionPerformed);

        txtSupplierGSTNo.addActionListener(this::txtSupplierGSTNoActionPerformed);

        txtSupplierAddress.addActionListener(this::txtSupplierAddressActionPerformed);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel50.setText("Order Product ");

        jLabel51.setText("Enter Product id");

        jLabel52.setText("Enter Quntity");

        btnAddMore.setText("Add more product");
        btnAddMore.addActionListener(this::btnAddMoreActionPerformed);

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jButton2.setText("Conform");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnAddMore)))
                .addGap(130, 130, 130))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel51)
                    .addComponent(btnAddMore))
                .addGap(47, 47, 47)
                .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Due Payment");

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setText("Order Details");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Per Unit");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Order Date");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Adavnce payment");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("valid rate date");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText(" Payment Mode");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Delivery Date");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Toal Amount");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Rate Per Unit");

        comboPaymentMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "UPI", "Bank Transfer", "Cheque" }));
        comboPaymentMode.addActionListener(this::comboPaymentModeActionPerformed);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Payment id");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Tatal Paid ");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Payment Date");

        comboOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order Placed", "Design Selected", "In Production", "Polishing / Finishing", "Ready for Delivery", "Delivered", "Payment Completed", " " }));

        comboPerUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Unit", "Gram (g)", "Kilogram (kg)", "Carat", "Piece", "Set", "Dozen" }));

        txtPaymetnId.addActionListener(this::txtPaymetnIdActionPerformed);

        txtRatePerUnit.addActionListener(this::txtRatePerUnitActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Submitt");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Order Status");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Update detatils");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboPaymentMode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboPerUnit, 0, 140, Short.MAX_VALUE)
                                .addComponent(txtTotalAMount)
                                .addComponent(txtTotalPaid))
                            .addComponent(orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(paymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPaymetnId, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRatePerUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                        .addComponent(txtAdvancePaymet))
                                    .addComponent(delivertDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(21, 21, 21))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDuePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valitdDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jButton1)
                .addGap(130, 130, 130)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(comboOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(delivertDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRatePerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valitdDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAMount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdvancePaymet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuePayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPaymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaymetnId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSeeproduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtProId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSeeproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSeeproduct5)
                                    .addComponent(txtSupplierid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupplierContact, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupplierCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnAddNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtProMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtProCategary, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnseeAllproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtproDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtprocarate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(txtNewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSupplierid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeeproduct4)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeeproduct5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(txtProId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProCategary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprocarate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeeproduct)
                    .addComponent(btnAddNewProduct))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnseeAllproduct)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprocarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprocarateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprocarateActionPerformed

    private void btnAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProductActionPerformed
        // TODO add your handling code here:
        ProductFrame newForm = new ProductFrame();
        newForm.setVisible(true);
    }//GEN-LAST:event_btnAddNewProductActionPerformed

    private void btnseeAllproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseeAllproductActionPerformed
        // TODO add your handling code here:
        ProductFind profind = new ProductFind();
        profind.setVisible(true);

    }//GEN-LAST:event_btnseeAllproductActionPerformed

    private void txtNewWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewWeightActionPerformed

    private void txtProCategaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProCategaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProCategaryActionPerformed

    private void txtProMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProMetalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProMetalActionPerformed

    private void txtPrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrNameActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnSeeproduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeproduct4ActionPerformed
        // TODO add your handling code here:
        String supllierID = txtSupplierid.getText();

        if (supllierID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Supplier id");
            return;
        }

        SupplierDAO dao = new SupplierDAO();
        Supplier sup = dao.getProductByID(supllierID);

        if (sup != null) {
            txtSupplierName.setText(sup.getName());
            txtSupplierContact.setText(sup.getContact());
            txtSupplierAddress.setText(sup.getAddress());
            txtSupplierCompanyName.setText(sup.getCompanyName());
            txtSupplierGSTNo.setText(sup.getGSTNO());
        } else {
            JOptionPane.showMessageDialog(this, "Supplier not Extis , Add new Supplier");
            return;
        }
    }//GEN-LAST:event_btnSeeproduct4ActionPerformed

    private void btnSeeproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeproductActionPerformed
        // TODO add your handling code here:
        String Prodid = txtProId.getText();

        if (Prodid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill product id for product detials");
            return;
        }

        ProductDAO dao = new ProductDAO();
        Product pro = dao.getProductByID(Prodid);

        if (pro != null) {
            txtPrName.setText(pro.getName());
            txtProCategary.setText(pro.getCategary());
            txtProMetal.setText(pro.getMetal());
            txtWeight.setText(String.valueOf(pro.getWeight()));
            txtproDesign.setText(pro.getDesign());
            txtprocarate.setText(pro.getCarat());

        } else {
            JOptionPane.showMessageDialog(this, "This id prodect not found , Please add product");
            return;
        }

    }//GEN-LAST:event_btnSeeproductActionPerformed

    private void txtSupplieridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplieridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplieridActionPerformed

    private void txtProIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProIdActionPerformed

    private void btnSeeproduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeproduct5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeeproduct5ActionPerformed

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void txtSupplierCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierCompanyNameActionPerformed

    private void txtSupplierContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierContactActionPerformed

    private void txtSupplierGSTNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierGSTNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierGSTNoActionPerformed

    private void txtSupplierAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierAddressActionPerformed

    private void btnAddMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoreActionPerformed
        // TODO add your handling code here:

        // Create a row panel
        JPanel rowPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));

        // Create text fields
        JTextField txtproOrdId = new JTextField(10);
        JTextField txtQtyField = new JTextField(8);
        JButton btnRemove = new JButton("Remove Item");

        // Store in list
        productFields.add(txtproOrdId);
        quantityFields.add(txtQtyField);

        // Labels (optional but good)
        JLabel lblProduct = new JLabel("Product ID:");
        JLabel lblQty = new JLabel("Quantity:");

        btnRemove.addActionListener(e -> {
            panelControl.remove(rowPanel);
            productFields.remove(txtproOrdId);
            quantityFields.remove(txtQtyField);

            panelControl.revalidate();
            panelControl.repaint();
        });

        // Add components to row
        rowPanel.add(txtproOrdId);
        rowPanel.add(txtQtyField);
        rowPanel.add(btnRemove);

        // Add row to main panel
        panelControl.add(rowPanel);

        // Refresh UI
        panelControl.revalidate();
        panelControl.repaint();

    }//GEN-LAST:event_btnAddMoreActionPerformed

    private void comboPaymentModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaymentModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaymentModeActionPerformed

    private void txtproDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproDesignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproDesignActionPerformed

    private void txtPaymetnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymetnIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymetnIdActionPerformed

    private void txtRatePerUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatePerUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatePerUnitActionPerformed

    private boolean validateItems() {

        if (productFields == null || productFields.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please add at least one product");
            return false;
        }

        String supplierid = txtSupplierid.getText().trim();

        if (supplierid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier ID cannot be empty");
            return false;
        }

        for (int i = 0; i < productFields.size(); i++) {

            String productid = productFields.get(i).getText().trim();
            String quantity = quantityFields.get(i).getText().trim();

            if (productid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Product ID cannot be empty (Row " + (i + 1) + ")");
                productFields.get(i).requestFocus();
                return false;
            }

            if (quantity.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be empty (Row " + (i + 1) + ")");
                quantityFields.get(i).requestFocus();
                return false;
            }

            try {
                int qty = Integer.parseInt(quantity);
                if (qty <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantity must be greater than 0 (Row " + (i + 1) + ")");
                    return false;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantity must be a number (Row " + (i + 1) + ")");
                return false;
            }
        }

        return true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (validateItems()) {
            JOptionPane.showMessageDialog(this, "Product Added Succefully");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!validateItems()) {
            return;
        }
        Date orderdate = orderDate.getDate();
        Date delevirayDate = delivertDate.getDate();
        String orderStatus = comboOrderStatus.getSelectedItem().toString().trim();
        String perUit = comboPerUnit.getSelectedItem().toString().trim();
        String ratePerUnit = txtRatePerUnit.getText();
        String totalAmount = txtTotalPaid.getText();
        String advancePayment = txtAdvancePaymet.getText();
        String duePayment = txtDuePayment.getText();
        String toalPaid = txtTotalPaid.getText();
        Date payDate = paymentDate.getDate();
        String paymentMode = comboPaymentMode.getSelectedItem().toString().trim();
        String paymentId = txtPaymetnId.getText();
        Date validDate = valitdDate.getDate();
        String sid = txtSupplierid.getText();

        if (comboPerUnit.getSelectedIndex() == 0 || comboPaymentMode.getSelectedIndex() == 0 || comboOrderStatus.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please fill all fields");
            return;
        }

        if (paymentMode.equalsIgnoreCase("Cash")) {

            // Cash → paymentId not required
            txtPaymetnId.setText(""); // optional (clear field)

        } else {

            // Other modes → paymentId required
            if (paymentId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Payment ID is required for " + paymentMode);
                txtPaymetnId.requestFocus();
                return;
            }
        }

        if (orderdate == null || delevirayDate == null || payDate == null) {
            JOptionPane.showMessageDialog(this, "Please provide  dates");
            return;
        }

        double TotalAmount;
        try {
            TotalAmount = Double.parseDouble(totalAmount);
            if (TotalAmount <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salary must be contain valid digits");
            return;
        }

        double RatePerUnit;
        try {
            RatePerUnit = Double.parseDouble(ratePerUnit);
            if (RatePerUnit <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salary must be contain valid digits");
            return;
        }

        double TotalPaid;
        try {
            TotalPaid = Double.parseDouble(toalPaid);
            if (TotalPaid <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salary must be contain valid digits");
            return;
        }

        double AdvancePayment;
        try {
            AdvancePayment = Double.parseDouble(advancePayment);
            if (AdvancePayment <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salary must be contain valid digits");
            return;
        }

        double DuePayment;
        try {
            DuePayment = Double.parseDouble(duePayment);
            if (DuePayment <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be Greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salary must be contain valid digits");
            return;
        }

        LocalDate OrderDate = orderdate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        LocalDate DeliveryDate = delevirayDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        LocalDate PaymentDate = payDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        LocalDate ValidDate = validDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        SupplierOrder supOrder = new SupplierOrder();
        supOrder.setOrderDate(OrderDate);
        supOrder.setDeliveryDate(DeliveryDate);
        supOrder.setPaymentdate(PaymentDate);
        supOrder.setTillEnd(ValidDate);
        supOrder.setOrderStatus(orderStatus);
        supOrder.setAmount(TotalAmount);
        supOrder.setAdvancePayment(AdvancePayment);
        supOrder.setDuePayment(DuePayment);
        supOrder.setTotalPayment(TotalPaid);
        supOrder.setPaymentMode(paymentMode);
        supOrder.setPaymentId(paymentId);
        supOrder.setSid(sid);

        SupplierQutation qutation = new SupplierQutation();
        qutation.setPerUnit(perUit);
        qutation.setRatePerUnit(RatePerUnit);
        qutation.setTillValid(ValidDate);

        for (int i = 0; i < productFields.size(); i++) {

            String pid = productFields.get(i).getText().trim();
            String qtyText = quantityFields.get(i).getText().trim();

            int qty = Integer.parseInt(qtyText);

            supOrder.getItems().add(new SupplieOrderItem(pid, qty));
        }
        SupplierDAO dao = new SupplierDAO();
        
        
        ProductDAO pro = new ProductDAO();

        try {
            String sid1 = supOrder.getSid();

            // 🔥 1. Check Supplier exists
            if (!dao.ExistSupplier(sid1)) {
                JOptionPane.showMessageDialog(this, "Supplier does not exist");
                return;
            }

            // 🔥 2. Check all Product IDs
            for (int i = 0; i < productFields.size(); i++) {

                String pid = productFields.get(i).getText().trim();

                if (!pro.ExitsProduct(pid)) {
                    JOptionPane.showMessageDialog(this, "Product not found: " + pid + " (Row " + (i + 1) + ")");
                    productFields.get(i).requestFocus();
                    return;
                }
            }

            // 🔥 3. If all valid → SAVE
            boolean res = dao.saveAllDate(qutation, supOrder);

            if (res) {
                JOptionPane.showMessageDialog(this, "Supplier Order Saved Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Supplier order not saved");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data not saved");
            ex.printStackTrace();
        }

//        SupplierDAO dao = new SupplierDAO();
//        try {
//            boolean res = dao.saveAllDate(qutation, supOrder);
//            if (res) {
//                JOptionPane.showMessageDialog(this, "Supplier Ordre Save Successfullu]y");
//            } else {
//                JOptionPane.showMessageDialog(this, "Supplier order not saved");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Data not save");
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SupplierDetailsUpdate supdetails = new SupplierDetailsUpdate();
        supdetails.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SupplierOrderfram().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMore;
    private javax.swing.JButton btnAddNewProduct;
    private javax.swing.JButton btnSeeproduct;
    private javax.swing.JButton btnSeeproduct4;
    private javax.swing.JButton btnSeeproduct5;
    private javax.swing.JButton btnseeAllproduct;
    private javax.swing.JComboBox<String> comboOrderStatus;
    private javax.swing.JComboBox<String> comboPaymentMode;
    private javax.swing.JComboBox<String> comboPerUnit;
    private com.toedter.calendar.JDateChooser delivertDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.toedter.calendar.JDateChooser orderDate;
    private java.awt.Panel panelControl;
    private com.toedter.calendar.JDateChooser paymentDate;
    private javax.swing.JTextField txtAdvancePaymet;
    private javax.swing.JTextField txtDuePayment;
    private javax.swing.JTextField txtNewWeight;
    private javax.swing.JTextField txtPaymetnId;
    private javax.swing.JTextField txtPrName;
    private javax.swing.JTextField txtProCategary;
    private javax.swing.JTextField txtProId;
    private javax.swing.JTextField txtProMetal;
    private javax.swing.JTextField txtRatePerUnit;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierCompanyName;
    private javax.swing.JTextField txtSupplierContact;
    private javax.swing.JTextField txtSupplierGSTNo;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierid;
    private javax.swing.JTextField txtTotalAMount;
    private javax.swing.JTextField txtTotalPaid;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtproDesign;
    private javax.swing.JTextField txtprocarate;
    private com.toedter.calendar.JDateChooser valitdDate;
    // End of variables declaration//GEN-END:variables
}
